config/routes.rb
Rails.application.routes.draw do
  get 'map/index'
  devise_for :users
  root 'users#top'
  get '/map_request', to: 'posts#map', as: 'map_request'
  get '/root_request', to: 'posts#root', as: 'root_request'
  get 'posts/' => 'posts#index'
  get 'management/' => 'users#management'

  resources :users
  resources :posts
  resources :places
  resources :favorites
  resources :images
  resources :comments
  resources :maps, only: [:index]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :posts, only: [:new, :create, :index, :show] do
      resource :favorites, only: [:create, :destroy]
      resource :comments, only: [:create, :edit, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :posts, dependent: :destroy
   has_many :comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   attachment :image

   has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
   has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
   has_many :following, through: :active_relationships, source: :followed
   has_many :followers, through: :passive_relationships, source: :follower

   validates :last_name, presence: true
   validates :last_name_kana, presence: true
   validates :first_name, presence: true
   validates :first_name_kana, presence: true
   validates :nickname, presence: true
   has_many  :favorite_posts, through: :favorites, source: :post

  def active_for_authentication?
    super && self.deleted == false
  end

   def follow(other_user)
      following << other_user
   end

  # ユーザーをフォロー解除する
   def unfollow(other_user)
      active_relationships.find_by(followed_id: other_user.id).destroy
   end

  # 現在のユーザーがフォローしてたらtrueを返す
   def following?(other_user)
      following.include?(other_user)
   end

   # ユーザーのステータスフィードを返す
  def feed
      following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
      Post.where("user_id IN (#{following_ids})", user_id: id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except: [:top]
	def top
	end

	def management
		if current_user.admin == false
			redirect_to user_path(current_user)
		else
			@search = User.ransack(params[:q])
			@results = @search.result.where(deleted: 'false')
		end
	end

	def index
		@user = current_user
		@posts = Post.where(user_id: @user.id, deleted: 'false').order(id: :desc).limit(3)
		#論理削除済みのユーザを取ってくる
		@delete_user = User.where(deleted: 'true')
		@search = Post.ransack(params[:q])
	    @results = @search.result.where(deleted: 'false')
	    #フォローしているユーザの最新投稿３件を持ってくる
	    @feed_items = current_user.feed.paginate(page: params[:page]).where(deleted: 'false').order(id: :desc).limit(8)
	    #いいねランキングを作る
	    favos = Favorite.group(:post_id).order('count(post_id) desc').pluck(:post_id)
	    @all_ranks = Post.where(id:favos,deleted:'false').limit(3)
	end

	def show
		@user = current_user
		@users = User.find(params[:id])
		if @users.deleted == true
			redirect_to users_path
		else
		    @search = Post.ransack(params[:q])
		    @results = @search.result.where(deleted: 'false')
		    @posts = @users.posts.where(deleted: 'false')
		    @favorites = Favorite.where(user_id: current_user.id)
		end
	end

	def edit
		@user = User.find(params[:id])
		if current_user.id == @user.id || current_user.admin == true
		else
	       redirect_to user_path(@user.id)
        end
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to user_path(@user.id)
    end

    def destroy
	    @users = User.find(params[:id])
	    @users.update(delete_user_params)
	    redirect_to root_path
    end

    def following
	    @title = "Following"
	    @user  = User.find(params[:id])
	    @users = @user.following.paginate(page: params[:page]).where(deleted: 'false')
	    render 'show_follow'
	end

	def followers
	    @title = "Followers"
	    @user  = User.find(params[:id])
	    @users = @user.followers.paginate(page: params[:page]).where(deleted: 'false')
	    render 'show_follow'
	end

	private
        def user_params
        	params.require(:user).permit(:last_name, :last_name_kana, :first_name, :first_name_kana, :nickname, :email, :image, :introduction)
        end
        def delete_user_params
            params.require(:user).permit(:deleted)
        end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="user-edit-box">
  	<%= form_for @user, url: user_path do |f| %>
  		<h4>Last name</h4>
  			<%= f.text_field :last_name, autofocus: true, id:"inputLastname", placeholder:"苗字"%>
  		<h4>Last name(kana)</h4>
  			<%= f.text_field :last_name_kana, autofocus: true, id:"inputLastnamekana", placeholder:"苗字かな"%>
  		<h4>First name</h4>
  			<%= f.text_field :first_name, autofocus: true, id:"inputFirstname", placeholder:"名前"%>
  		<h4>First name(kana)</h4>
  			<%= f.text_field :first_name_kana, autofocus: true, id:"inputFirstname", placeholder:"名前かな"%>
  		<h4>Nickname</h4>
  			<%= f.text_field :nickname, autofocus: true, id:"inputNickname", placeholder:"ニックネーム"%>
  		<h4>E-mail</h4>
  			<%= f.text_field :email, autofocus: true, id:"inputEmail", placeholder:"E-mail"%>
  		<h4>User Image</h4>
  	        <%= f.attachment_field :image, class: "image", type:'file' %>
  		<br>
  		<div class="preview"></div>
  		<h4>Introduction</h4>
  				<%= f.text_area :introduction, autofocus: true, class:"introduction", id:"inputIntroduction", placeholder:"自己紹介"%><br>
  			<%= f.submit 'User Update',class: 'user-edit-btn', style:"width:150px; margin-top:10px; margin-bottom:30px;" %>
  	<% end %>
  </div>
</div>

<script>
	$(function(){
  //画像ファイルプレビュー表示のイベント追加 fileを選択時に発火するイベントを登録
  $('form').on('change', 'input[type="file"]', function(e) {
    var file = e.target.files[0],
        reader = new FileReader(),
        $preview = $(".preview");
        t = this;

    // 画像ファイル以外の場合は何もしない
    if(file.type.indexOf("image") < 0){
      return false;
    }

    // ファイル読み込みが完了した際のイベント登録
    reader.onload = (function(file) {
      return function(e) {
        //既存のプレビューを削除
        $preview.empty();
        // .prevewの領域の中にロードした画像を表示するimageタグを追加
        $preview.append($('<img>').attr({
                  src: e.target.result,
                  width: "200px",
                  class: "preview",
                  title: file.name
              }));
      };
    })(file);

    reader.readAsDataURL(file);
  });
});

</script>

app/views/users/index.html.erb
<div id="container">
	<div id="theTarget">
		<div class="Top1"><p>∴さて・・・・ どこへ行こうか？</p></div>
		<div class="Top2"><p>∴さて・・・・ どこへ行こうか？</p></div>
		<div class="Top3"><p>∴さて・・・・ どこへ行こうか？</p></div>
		<div class="Top4"><p>∴さて・・・・ どこへ行こうか？</p></div>
		<div class="Top5"><p>∴さて・・・・ どこへ行こうか？</p></div>
	</div>
</div>


<div class="container">
	<div class="col-sm-4">
	<div class="user-box" style="text-align: center;">
		<span><%= link_to user_path(current_user.id) do %><%= attachment_image_tag @user, :image, :fill, 200, 200, class:"image-to-circle user-image", fallback: "No_image.png",size: '200x200' %><% end %></span><br>
		<p><%= @user.nickname %></p>
		<p><%= @user.introduction %></p>
	<% @users ||= current_user %>
	  <div class="stats follow-zone">
	    <a href="<%= following_user_path(@users) %>" class="follow-btn" style="text-decoration:none; margin: 5px;">
	      <strong id="following" class="stat">
	        <%= @users.following.where(deleted: 'false').count %>
	      </strong>
	      following
	    </a><br>
	    <a href="<%= followers_user_path(@users) %>" class="follow-btn" style="text-decoration:none;">
	      <strong id="followers" class="stat">
	        <%= @users.followers.where(deleted: 'false').count %>
	      </strong>
	      followers
	    </a>
	  </div>
	</div>
	<div class="user-box ranking-box">
		<div class="following-post-title"><i class="fas fa-crown"></i> Favorite Ranking <i class="fas fa-crown"></i></div>
	      <% @all_ranks.each do |rank| %>
	        <li class=""><%= link_to post_path(rank.id) do %>
	                      <%= attachment_image_tag rank.images.last, :image, fallback: "No_image.png",size: '100x100', class:"ranking-image", style:"object-fit: cover;" %>
	          <span style="padding-left: 15px;"><%= rank.title %><% end %></span></li>
	      <% end %>
	</div>
</div>

<div class="col-sm-6">
	<%= render 'posts/list', results: @results, search: @search %>
</div>
	<div class="col-sm-7">
		<div class="index-post-box">
			<div class="fpost-list-nav">
				<ul>
					<% @feed_items.where.not(user_id: @delete_user).each do |post| %>
						<li><%= link_to post_path(post.id) do %>
						    <%= attachment_image_tag post.images.last, :image, fallback: "No_image.png",size: '150x150', class:"post-image", style:"object-fit: cover;" %>
						            <% end %>
						    <%= link_to post.title, post_path(post.id), class:"post-title" %>
						</li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
	<div class="col-sm-7">
		<div class="index-your-box">
		<div class="post-list-nav">
			<% @posts.each do |ypost| %>
				<li class="post-nav-item"><%= link_to post_path(ypost.id) do %>
			    	<%= attachment_image_tag ypost.images.last, :image, fallback: "No_image.png",size: '150x150', class:"post-image", style:"object-fit: cover;" %>
			        <% end %>
			    	<%= link_to ypost.title, post_path(ypost.id), class:"post-title" %>
			    </li>
			<% end %>
		</div>
		</div>
	</div>
</div>

</div>
<script>

  $("#theTarget").skippr({
      // スライドショーの変化 ("fade" or "slide")
      transition : 'fade',
      // 変化に係る時間(ミリ秒)
      speed : 1000,
      // easingの種類
      easing : 'easeOutQuart',
      // ナビゲーションの形("block" or "bubble")
      navType : 'block',
      // 子要素の種類("div" or "img")
      childrenElementType : 'div',
      // ナビゲーション矢印の表示(trueで表示)
      arrows : false,
      // スライドショーの自動再生(falseで自動再生なし)
      autoPlay : true,
      // 自動再生時のスライド切替間隔(ミリ秒)
      autoPlayDuration : 6000,
      // キーボードの矢印キーによるスライド送りの設定(trueで有効)
      keyboardOnAlways : false,
      // 一枚目のスライド表示時に戻る矢印を表示するかどうか(falseで非表示)
      hidePrevious : false
  });
</script>

app/views/users/management.html.erb
<div class="user-index">
	<% provide(:first_name || :last_name, 'Users') %>
	<div class="search-zone" style="float:left">
		<%= search_form_for @search, url: management_path, method: :get do |f| %>
		  <div class="form-group">
		    <%= f.label :first_name_cont, "Search" %>
		    <%= f.text_field :first_name_or_last_name_or_nickname_cont, class: "form-control" %>
		  </div>
		  <div class="search-btn-zone">
		  	<%= f.submit "Let's Search", class:"search-btn" %>
		  </div>
		</div>
	<% end %>
	<table class="clip-box-b">
		<% @results.each do |user| %>
			<tr>
				<th><span><%= link_to user_path(user.id) do %>
					<%= attachment_image_tag user, :image, fallback: "No_image.png",size: '80x80', class:"user-image" %>
					<% end %></span></th>
				<th><%= link_to user.nickname, user_path(user.id), class:"user-name" %></th>
			<% end %>
			</tr>
	</table>
</div>

app/views/users/show.html.erb
<div class="container">

<div class="col-sm-3">
<div class="user-action-zone">
  <%= attachment_image_tag @users, :image, :fill, 200, 200, class:"image-to-circle", fallback: "No_image.png",size:'200x200' %><br>
  <% if @users.id == current_user.id || current_user.admin == true %>
  	<%= @users.last_name %>
  	<%= @users.first_name %><br>
  <% end %>
  <%= @users.nickname %><br>
  <%= @users.introduction %>

  <% @users ||= current_user %>
  <div class="stats follow-zone">
    <a href="<%= following_user_path(@users) %>" class="follow-btn" style="text-decoration:none; margin: 5px;">
      <strong id="following" class="stat">
        <%= @users.following.where(deleted: 'false').count %>
      </strong>
      following
    </a><br>
    <a href="<%= followers_user_path(@users) %>" class="follow-btn" style="text-decoration:none;">
      <strong id="followers" class="stat">
        <%= @users.followers.where(deleted: 'false').count %>
      </strong>
      followers
    </a>
  </div>


  <%= render 'relationships/list', users: @users %>

  	<% if @users.id == current_user.id || current_user.admin == true %>
  		<%= link_to "User Edit", edit_user_path(@users.id), class:"edit_user_#{@users.id} user-edit-btn", style:"text-decoration:none; margin-bottom:5px;" %><br>
  		<%= link_to "Quit", user_path(@users.id, :user => {:deleted => 'true'}), method: :delete, class:"destroy_user_#{@users.id} quit-btn", style:"text-decoration:none;", "data-confirm" => "Arkheを退会します。よろしいですか？" %>
  	<% end %>
  </div>
</div>

  <%= render 'posts/list', results: @results, search: @search %>
  <div class="col-sm-8">
    <div class="your-post-box">
    <div class="post-action-zone">
  		<% @posts.each do |post| %>
        <span class="post-index"><%= link_to post_path(post.id) do %>
          <li class="your-nav-item"><%= attachment_image_tag post.images.last, :image, fallback: "No_image.png",size:'80x80', class:"post-image", style:"object-fit: cover;" %>
          <% end %>
        </span>
  			<%=link_to post.title, post_path(post.id), class:"post-title" %>
        <% if @user == current_user %>
              <%= link_to "Post Edit", edit_post_path(post.id), class:"post-edit-btn", style:"text-decoration:none;" %>
              <%= link_to "Post Delete", post_path(post.id, :post => {:deleted => 'true'}), method: :delete, class:"destroy_post#{post.id} post-delete-btn", style:"text-decoration:none;", "data-confirm" => "投稿を削除します。よろしいですか？" %>
          <% end %></li>
  		<% end %>
    </div>
  </div>
  </div>

<% if @users.id == current_user.id || current_user.admin == true %>
  <div class="col-sm-8">
    <div class="fav-post-box">
      <div class="fav-list-nav">
        <ul>
          <% @user.favorite_posts.each do |fpost| %>
            <li class="your-nav-item">
              <span class="post-index"><%= link_to post_path(fpost.id) do %>
            <%= attachment_image_tag fpost.images.last, :image, fallback: "No_image.png",size:'110x110', class:"post-image", style:"object-fit: cover;" %></span>
          <% end %>
        <%=link_to fpost.title, post_path(fpost.id), class:"post-title" %></li>
      <% end %>
      </span>
    </ul>
    </div>
  </div>
  </div>
  <% else %>
<% end %>

</div>

app/views/users/show_follow.html.erb
<div class="container">
  <div class="clip-box-c">
    <div class='follow-title'>
      <% provide(:title, @title) %>
      <h3><%= @title %></h3>
    </div>
        <section class="stats">
          <% if @users.any? %>
            <div class="user-index">
              <table>
              <% @users.each do |user| %>
              <tr>
                  <th><span><%= link_to user_path(user.id) do %>
                          <%= attachment_image_tag user, :image, :fill, 70, 70, fallback: "No_image.png",size: '70x70', class:"user-image" %>
                        <% end %>
                  </span></th>
                  <th><%= link_to user.nickname, user_path(user.id) %></th>
                <% end %>
              </tr><br>
              </table>
            </div>
          <% end %>
        </section>
      </aside>
      <div class="col-md-8">
        <% if @users.any? %>
          <ul class="users follow">
          </ul>
          <%= will_paginate %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/top.html.erb
<div id="top-page">
	<div class='text-box'>
		<div class="text-text">体が心を変え、心が行動を変え、<br>
			行動が結果を変える <br>
			<p style="font-size: 30px;">Amy Cuddy (1972~ ）</p></div>
	</div>
</div>

<div class="top-text1">
	<div class='text-box1'>
		<div data-scroll>
			<p style="font-size: 30px;">最近、運動してますか？<br><br></p>
		</div>
		<div data-scroll>
			<p style="font-size: 30px;">待ちに待った休日。<br><br></p>
		</div>
		<div data-scroll>
			<p style="font-size: 30px;">せっかくだからどこかへ出かけようとするけれど、<br><br></p>
		</div>
		<div data-scroll>
			<p style="font-size: 30px;">結局家に引きこもったまま１日が終わる…。<br><br></p>
		</div>
		<div data-scroll>
			<p style="font-size: 30px;">そんな経験ありませんか？</p>
		</div>
	</div>
</div>

<div class="top-text2">
	<div class='text-box2'>
		<div data-scroll >
			<div data-scroll>
				<p style="font-size: 35px;">How to use<br><br></p>
			</div>
			<div data-scroll>
				<p style="font-size: 30px;">お散歩に行った場所を投稿する。<br><br></p>
			</div>
			<div data-scroll>
				<p style="font-size: 30px;">行ってみたい場所を検索して、散歩コースを見てみる。<br><br></p>
			</div>
			<div data-scroll>
				<p style="font-size: 30px;">お気に入りのユーザをフォローして、散歩の投稿を見てみる。<br><br></p>
			</div>
			<div data-scroll>
				<p style="font-size: 30px;">そんな感じのサイトです。</p>
			</div>
		</div>
	</div>
</div>

<div class="top-text3">
	<div class='text-box3'>
		<div data-scroll >
			<div data-scroll>
				<p style="font-size: 35px;">Contact Us<br><br></p>
			</div>
			<div data-scroll>
				<p style="font-size: 30px;">ご不明な点やご質問、ご要望などございましたら<br><br></p>
			</div>
			<div data-scroll>
				<p style="font-size: 30px;">下記のアドレスまでご連絡お願い致します。<br><br></p>
			</div>
			<div data-scroll>
				<p style="font-size: 30px;">fuku0118yf★gmail.com<br><br></p>
			</div>
			<div data-scroll>
				<p style="font-size: 30px;">★の部分を@に置き換えて下さい。</p>
			</div>
		</div>
</div>
    <span id="back">
      <a href="#">
        <img src="/images/arrow.png" alt="">
      </a>
    </span>
</div>


<script>

$(function() {
  $('#back a').on('click',function(){
    $('body, html').animate({
      scrollTop:0
    }, 400);
      return false;
  });
});

</script>

<script src="/assets/ScrollTrigger.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function(){
  var trigger = new ScrollTrigger();
});
</script>