config/routes.rb
Rails.application.routes.draw do
  get 'map/index'
  devise_for :users
  root 'users#top'
  get '/map_request', to: 'posts#map', as: 'map_request'
  get '/root_request', to: 'posts#root', as: 'root_request'
  get 'posts/' => 'posts#index'
  get 'management/' => 'users#management'

  resources :users
  resources :posts
  resources :places
  resources :favorites
  resources :images
  resources :comments
  resources :maps, only: [:index]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :posts, only: [:new, :create, :index, :show] do
      resource :favorites, only: [:create, :destroy]
      resource :comments, only: [:create, :edit, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :images, dependent: :destroy
	has_many :images, inverse_of: :post
  	accepts_attachments_for :images, attachment: :image
	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :places
	accepts_nested_attributes_for :places, allow_destroy: true

	validates :title, presence: true
	validates :text, presence: true
	has_many  :favorite_posts, through: :favorites, source: :user

	def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
	def index
      #論理削除済みのユーザを取ってくる
      @delete_user = User.where(deleted: 'true')
      #(params[:q])に検索パラメーターが入り、Productテーブルを検索する@searchオブジェクトを生成
      @search = Post.ransack(params[:q])
      #検索結果を表示する@resultsオブジェクトを生成
      @results = @search.result.where(deleted: 'false')
  end

  def new
  		@post = Post.new
      p  = ENV["GMAP"]
      #@postに関連づけたimages,placesをbuild
  		@post.images.build
      @post.places.build
	end

    def show
      @post = Post.find(params[:id])
      @user = User.find(@post.user_id)
      if @user.deleted == true || @post.deleted == true
        redirect_to users_path
      else
        @comment = Comment.new
        @search = Post.ransack(params[:q])
        @results = @search.result
        @places = @post.places
        #root()のメソッド呼び出し
        root()
      end
  end

	def create
      @post = Post.new(post_params)
      @post.user_id = current_user.id
      if @post.save
          redirect_to post_path(@post.id)
      else
          @post = Post.new
          @image = Image.new
          flash.now[:error] = "Any error has occurred. Please check your post."
          render :new
      end
  end

  def edit
      @user = current_user
      @post = Post.find(params[:id])
      #root()のメソッド呼び出し
      root()
      if current_user.id == @post.user_id || current_user.admin == true
      else
        redirect_to post_path(@post.id)
      end
  end

	def update
  		@post = Post.find(params[:id])
  		@post.update(post_params)
  		redirect_to post_path(@post.id)
	end

	def destroy
  		@post = Post.find(params[:id])
  		@post.update(delete_post_params)
      #今はとりあえずユーザのパスへ遷移
  		redirect_to user_path(current_user.id)
	end

  def map
      results = Geocoder.search(params[:address])
      @latlng = results.first.coordinates
      # これでmap.js.erbで、経度緯度情報が入った@latlngを使える。
      respond_to do |format|
        format.js
      end
  end

  def root()
      @post = Post.find(params[:id])
      @user = User.find(@post.user_id)
      #
      @data = []
      @post.places.order(order:"ASC").each do |place|
        @address = place.address
        @data << Geocoder.coordinates(@address)
      end
      gon.locations = @data
      gon.location = @data.first
  end

	private
    def post_params
        params.require(:post).permit(:title, :user_id, :text, :deleated,
          images_images: [], places_attributes: [:address, :order, :_destroy])
    end
    def delete_post_params
        params.require(:post).permit(:deleted)
    end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/_infowindow.html.erb
<div id="info-window-name">
  <%= link_to "#{place.name}", place %>
</div>
<div id="info-wondow-btn">
  <%= button_tag "経路に追加", id: "btn-add", class: "btn btn-primary btn-sm", 
    onclick: "addPlace('#{place.name}',#{place.latitude}, #{place.longitude})" %>
</div>

app/views/posts/_list.html.erb
<% provide(:title, 'All posts') %>
	<div class="search-zone" style="float:left">
	<%= search_form_for search  do |f| %>
	  <div class="form-group">
	    <%= f.label :title_cont, "Search" %>
	    <%= f.text_field :title_or_text_cont, class: "form-control" %>
	  </div>
	  <div class="search-btn-zone">
	  	<%= f.submit "Let's Search", class:"search-btn" %>
	  </div>
	</div>
<% end %>

app/views/posts/_place_fields.html.erb
<div class='nested-fields' id="placef" style="padding: 5px;">
  <%#= f.inputs do %>
    <%= f.text_field :order, placeholder:"order" %>
    <%= f.text_field :address, id:"address", placeholder:"address" %>
    <%= link_to_remove_association "remove place", f, id:"removeb", class:"post-remove-btn" %>
  <%# end %>
</div>

app/views/posts/edit.html.erb
<div class="post-box">
<div class="container">
    <div class="new-post-box">
        <% if flash[:error] %>
          <p id="error"><%= flash[:error] %></p>
        <% end %>
        <h2>Post Edit</h2>
        <h2>Gmap</h2>
    </div>

  <div id="map"></div>

<div class="new-post-box clip-box-a">
    <table class="post-table">
        <p style="font-family: 'Comic Sans MS',sans-serif; font-size: 20px;">Routes</p>
            <% @post.places.order(order:"ASC").each do |p| %>
                <tr>
                  <th><%= p.address %></th>
                  <% if current_user == @user || current_user.admin == 'true' %>
                    <th><%= link_to "place delete", place_path(p.id), method: :delete, class:"destroy_p_#{p.id} place-remove-btn", "data-confirm" => "場所を削除します。よろしいですか？" %></th>
                    <% else %>
                <% end %>
            </tr>
        <% end %>
    </table>
</div>

<div class="new-post-box clip-box-a">
    <table class="post-table">
        <p style="font-family: 'Comic Sans MS',sans-serif; font-size: 20px;">Images</p>
            <% @post.images.each do |image| %>
                <tr>
                  <th><%= attachment_image_tag image, :image, :fill, 200, 200 %></th>
                  <% if current_user == @user || current_user.admin == 'true' %>
                    <th><%= link_to "image delete", image_path(image.id), method: :delete, class:"destroy_image_#{image.id} place-remove-btn", "data-confirm" => "画像を削除します。よろしいですか？" %></th>
                    <% else %>
                <% end %>
            </tr>
        <% end %>
    </table>
</div>

    <div style="width: 80%; margin: auto;">
        <div id="preview_result">Image preview</div>
    </div>

<div class="new-post-box clip-box-a">
    <%= form_for @post, url: post_path do |f| %>
        <h3>Where You went</h3>
              <div id='places'>
                <%= f.fields_for :places do |place| %>
                <%= render 'place_fields', :f => place %>
                <% end %>
                <div class='links'>
                    <%= link_to_add_association 'add place', f, :places, class:"post-add-btn" %>
                </div>
              </div>

            <b>Title</b><br>
              <%= f.text_field :title, autofocus: true, id:"inputLastname", placeholder:"Title" %><br>
            <b>Text</b><br>
              <%= f.text_area :text, autofocus: true, id:"inputLastnamekana", placeholder:"Text", :size=>"50x5" %>
            <h3>Image Post</h3>
                <%= f.attachment_field :images_images, multiple: true, class:"image", type:"file", id:"input_file", onchange:"preview_file(this.id);"%>
                <div class="post-btn-zone">
                    <%= f.submit 'Post Edit', class: 'post-btn' %>
                </div>
          <% end %>
        </div>
    </div>
</div>


<script>
// プレビュー関数(引数 ⇒ inputタグのid)
function preview_file(id){

    // 対象要素を取得
    var target_element = document.getElementById(id);

    // 結果コードを格納する変数
    var result_code = '';

    // アップした画像の数だけ処理
    for (var i = 0; i < document.getElementById(id).files.length; i++){

        // 画像のURLを取得
        var img_url = window.URL.createObjectURL(document.getElementById(id).files[i]);

        // コードを更新
        result_code += '<img src="' + img_url + '" alt="プレビュー">';

    }

    // プレビューを出力
    document.getElementById('preview_result').innerHTML = result_code;

}
</script>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>

　let mapInstance
  function initMap() {
    var bounds = new google.maps.LatLngBounds();
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 11,
      center: { lat: gon.location[0], lng: gon.location[1] },
      styles: [
        {
            "featureType": "administrative",
            "elementType": "labels.text.fill",
            "stylers": [
                {
                    "color": "#6195a0"
                }
            ]
        },
        {
            "featureType": "administrative.province",
            "elementType": "geometry.stroke",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "landscape",
            "elementType": "geometry",
            "stylers": [
                {
                    "lightness": "0"
                },
                {
                    "saturation": "0"
                },
                {
                    "color": "#f5f5f2"
                },
                {
                    "gamma": "1"
                }
            ]
        },
        {
            "featureType": "landscape.man_made",
            "elementType": "all",
            "stylers": [
                {
                    "lightness": "-3"
                },
                {
                    "gamma": "1.00"
                }
            ]
        },
        {
            "featureType": "landscape.natural.terrain",
            "elementType": "all",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "poi",
            "elementType": "all",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "poi.park",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#bae5ce"
                },
                {
                    "visibility": "on"
                }
            ]
        },
        {
            "featureType": "road",
            "elementType": "all",
            "stylers": [
                {
                    "saturation": -100
                },
                {
                    "lightness": 45
                },
                {
                    "visibility": "simplified"
                }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "all",
            "stylers": [
                {
                    "visibility": "simplified"
                }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#fac9a9"
                },
                {
                    "visibility": "simplified"
                }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "labels.text",
            "stylers": [
                {
                    "color": "#4e4e4e"
                }
            ]
        },
        {
            "featureType": "road.arterial",
            "elementType": "labels.text.fill",
            "stylers": [
                {
                    "color": "#787878"
                }
            ]
        },
        {
            "featureType": "road.arterial",
            "elementType": "labels.icon",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "transit",
            "elementType": "all",
            "stylers": [
                {
                    "visibility": "simplified"
                }
            ]
        },
        {
            "featureType": "transit.station.airport",
            "elementType": "labels.icon",
            "stylers": [
                {
                    "hue": "#0a00ff"
                },
                {
                    "saturation": "-77"
                },
                {
                    "gamma": "0.57"
                },
                {
                    "lightness": "0"
                }
            ]
        },
        {
            "featureType": "transit.station.rail",
            "elementType": "labels.text.fill",
            "stylers": [
                {
                    "color": "#43321e"
                }
            ]
        },
        {
            "featureType": "transit.station.rail",
            "elementType": "labels.icon",
            "stylers": [
                {
                    "hue": "#ff6c00"
                },
                {
                    "lightness": "4"
                },
                {
                    "gamma": "0.75"
                },
                {
                    "saturation": "-68"
                }
            ]
        },
        {
            "featureType": "water",
            "elementType": "all",
            "stylers": [
                {
                    "color": "#eaf6f8"
                },
                {
                    "visibility": "on"
                }
            ]
        },
        {
            "featureType": "water",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#c7eced"
                }
            ]
        },
        {
            "featureType": "water",
            "elementType": "labels.text.fill",
            "stylers": [
                {
                    "lightness": "-49"
                },
                {
                    "saturation": "-53"
                },
                {
                    "gamma": "0.79"
                }
            ]
        }
    ]


    });
    for(var i = 0; i < gon.locations.length; i++){
      marker = new google.maps.Marker({
        position: { lat: gon.locations[i][0], lng: gon.locations[i][1] },
        // title: gon.locations[i].name,
      });
    }
    //ルート表示
        var rendererOptions = {
            suppressMarkers : false,
            map: map,
        }
        var directionsDisplay = new google.maps.DirectionsRenderer(rendererOptions);
        var directionsService = new google.maps.DirectionsService();
        var points ={};
        var origin; // 開始地点
        var destination; // 終了地点
        var waypoints = []; // 経由地点

            //origin, destination, waypointsを設定する
            for (var i = 0; i < gon.locations.length; i++) {
                points = {lat : gon.locations[i][0], lng : gon.locations[i][1]};
                // points[i] = new google.maps.LatLng(gon.locations[i][0],gon.locations[i][1]);
                if (i == 0){
                    origin = points;
                } else if (i == gon.locations.length-1){
                    destination = points;
                } else {
                    var waylocations = new google.maps.LatLng(points.lat, points.lng);
                    waypoints.push( {location: waylocations, stopover: true} );
                }
            }

            // リクエスト作成
            var request = {
                origin:      origin,
                destination: destination,
                waypoints: waypoints,
                travelMode:  google.maps.TravelMode.WALKING,
                optimizeWaypoints: false
            };

            // ルートサービスのリクエスト
            directionsService.route(request, function(response, status) {

                if (status == google.maps.DirectionsStatus.OK) {
                    // 結果を表示する
                    directionsDisplay.setDirections(response);
                }
                var data = response.routes[0].legs;
                var dis = 0;
                var sec = 0;
                for (var i = 0; i < data.length; i++) {
                    sec += data[i].duration.value;
                    dis += data[i].distance.value;
                }
                var d = document.createElement("span");
                d.setAttribute("id", "distance");
                var dresult = Math.round(dis*100/1000) / 100;
                d.innerHTML     = dresult + "km";
                document.getElementById("distance").appendChild(d);

                var t = document.createElement("span");
                t.setAttribute("id", "time");
                var sresult = Math.round(sec*100/3600) / 100;
                t.innerHTML     = sresult  + "時間";
                document.getElementById("time").appendChild(t);
            });

      bounds.extend (marker.position);
      map.fitBounds (bounds);
    //ルート表示
  }

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GMAP']%>&callback=initMap" async defer></script>

app/views/posts/index.html.erb
<div class="container">
	<div class="user-index">
		<% provide(:title, 'All posts') %>
		<%= render 'posts/list', results: @results, search: @search %>
	</div>
</div>

<div class="result-post-box">
	<table class="results">
		<% if @results.any? %>
	 		<% @results.where.not(user_id: @delete_user).each do |result| %>
	 		<tr>
		 		<td><span><%= link_to post_path(result.id) do %>
		            <%= attachment_image_tag result.images.last, :image, fallback: "No_image.png",size: '70x70', class:"post-image", style:"object-fit: cover;" %></td>
		   		<td><p><%= link_to result.title, post_path(result.id), class:"post-title" %></p><% end %></span></td>
		   	</tr>
		 	<% end %>
		<% end %>
	</table>
</div>


<script>
	$("tr[data-link]").click(function() {
	  window.location = this.data("data-link")
	})
</script>

app/views/posts/map.js.erb
(function(){
  // 位置情報をもつ変数を用意
  let pos = new google.maps.LatLng(
   <%= @latlng[0] %>, //latitude
   <%= @latlng[1] %>  //longitude
  );

  mapInstance.setCenter(pos)
  let marker = new google.maps.Marker({
    map: mapInstance,
    position: pos
  });
})()


var rendererOptions = {
    suppressMarkers : true
}
var directionsDisplay = new google.maps.DirectionsRenderer(rendererOptions);
var directionsService = new google.maps.DirectionsService();

// 複数地点のルートを検索する
function search() {
    var points = $('marker');

    // 2地点以上のとき
    if (points.length >= 2){
        var origin; // 開始地点
        var destination; // 終了地点
        var waypoints = []; // 経由地点

        // origin, destination, waypointsを設定する
        for (var i = 0; i < points.length; i++) {
            points[i] = new google.maps.LatLng($(points[i]).attr("data-lat"), $(points[i]).attr("data-lng"));
            if (i == 0){
                origin = points[i];
            } else if (i == points.length-1){
                destination = points[i];
            } else {
                waypoints.push({ location: points[i], stopover: true });
            }
        }
        // リクエスト作成
        var request = {
            origin:      origin,
            destination: destination,
            waypoints: waypoints,
            travelMode:  google.maps.TravelMode.DRIVING
        };
        // ルートサービスのリクエスト
        directionsService.route(request, function(response, status) {
            if (status == google.maps.DirectionsStatus.OK) {
                // 結果を表示する
                directionsDisplay.setDirections(response);
            }
        });
    }
}

app/views/posts/new.html.erb
<div class="post-box">
    <div class="new-post-box">
    	<h2>New Post</h2>
        <% if flash[:error] %>
          <p id="error"><%= flash[:error] %></p>
        <% end %>
    	<h2 style="font-family: 'Comic Sans MS',sans-serif;">Gmap</h2>
	<!-- form_withはデフォルトでremote: trueの挙動になります -->
    	<%= form_with url: map_request_path, method: :get do |f|%>
    	  <%= f.text_field :address, style:"margin-bottom: 10px;" %>
    	  <%= f.submit 'Map Search', class:"post-search-btn", style:"margin-bottom: 10px;" %>
    	<% end %>
    </div>
	<div id="map">
	</div>

    <div style="width: 80%; margin: auto; margin-top:10px;">
        <div id="preview_result">Image preview</div>
    </div>

    <div class="new-post-box clip-box-a">
        	<%= form_for @post, url: posts_path do |f| %>
        		<h3>Where You went</h3>
        	    <div id='places'>
        		      <%= f.fields_for :places do |place| %>
        		        <%= render 'place_fields', :f => place %>
        		      <% end %>
        		      <div class='links'>
        		        <%= link_to_add_association 'add place', f, :places, class:"post-add-btn" %>
        		    </div>
            	</div>

        		<b>Title</b><br>
        			<%= f.text_field :title, autofocus: true, id:"inputLastname", placeholder:"Title"%><br>
        		<b>Text</b><br>
        			<%= f.text_area :text, autofocus: true, id:"inputLastnamekana", placeholder:"Text", :size=>"50x5"%>
        		<h3>Image Post</h3>
        			<%= f.attachment_field :images_images, multiple: true, class:"image", type:"file", id:"input_file", onchange:"preview_file(this.id);"%>
                    <div class="post-btn-zone">
        		      <%= f.submit 'New Post',class: 'post-btn' %>
                    </div>
        	<% end %>
    </div>
</div>

<script>
// プレビュー関数(引数 ⇒ inputタグのid)
function preview_file(id){

    // 対象要素を取得
    var target_element = document.getElementById(id);

    // 結果コードを格納する変数
    var result_code = '';

    // アップした画像の数だけ処理
    for (var i = 0; i < document.getElementById(id).files.length; i++){

        // 画像のURLを取得
        var img_url = window.URL.createObjectURL(document.getElementById(id).files[i]);

        // コードを更新
        result_code += '<img src="' + img_url + '" alt="プレビュー">';

    }

    // プレビューを出力
    document.getElementById('preview_result').innerHTML = result_code;

}
</script>
<script>
  let mapInstance //この変数はmap.js.erbでも使うのでタイプミスに注意

  function initMap(){
    mapInstance = new google.maps.Map(document.getElementById('map'), {
	    center: {lat: 35.658, lng: 139.7},
	    zoom: 14,
	    styles: [
        {
            "featureType": "administrative",
            "elementType": "labels.text.fill",
            "stylers": [
                {
                    "color": "#6195a0"
                }
            ]
        },
        {
            "featureType": "administrative.province",
            "elementType": "geometry.stroke",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "landscape",
            "elementType": "geometry",
            "stylers": [
                {
                    "lightness": "0"
                },
                {
                    "saturation": "0"
                },
                {
                    "color": "#f5f5f2"
                },
                {
                    "gamma": "1"
                }
            ]
        },
        {
            "featureType": "landscape.man_made",
            "elementType": "all",
            "stylers": [
                {
                    "lightness": "-3"
                },
                {
                    "gamma": "1.00"
                }
            ]
        },
        {
            "featureType": "landscape.natural.terrain",
            "elementType": "all",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "poi",
            "elementType": "all",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "poi.park",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#bae5ce"
                },
                {
                    "visibility": "on"
                }
            ]
        },
        {
            "featureType": "road",
            "elementType": "all",
            "stylers": [
                {
                    "saturation": -100
                },
                {
                    "lightness": 45
                },
                {
                    "visibility": "simplified"
                }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "all",
            "stylers": [
                {
                    "visibility": "simplified"
                }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#fac9a9"
                },
                {
                    "visibility": "simplified"
                }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "labels.text",
            "stylers": [
                {
                    "color": "#4e4e4e"
                }
            ]
        },
        {
            "featureType": "road.arterial",
            "elementType": "labels.text.fill",
            "stylers": [
                {
                    "color": "#787878"
                }
            ]
        },
        {
            "featureType": "road.arterial",
            "elementType": "labels.icon",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "transit",
            "elementType": "all",
            "stylers": [
                {
                    "visibility": "simplified"
                }
            ]
        },
        {
            "featureType": "transit.station.airport",
            "elementType": "labels.icon",
            "stylers": [
                {
                    "hue": "#0a00ff"
                },
                {
                    "saturation": "-77"
                },
                {
                    "gamma": "0.57"
                },
                {
                    "lightness": "0"
                }
            ]
        },
        {
            "featureType": "transit.station.rail",
            "elementType": "labels.text.fill",
            "stylers": [
                {
                    "color": "#43321e"
                }
            ]
        },
        {
            "featureType": "transit.station.rail",
            "elementType": "labels.icon",
            "stylers": [
                {
                    "hue": "#ff6c00"
                },
                {
                    "lightness": "4"
                },
                {
                    "gamma": "0.75"
                },
                {
                    "saturation": "-68"
                }
            ]
        },
        {
            "featureType": "water",
            "elementType": "all",
            "stylers": [
                {
                    "color": "#eaf6f8"
                },
                {
                    "visibility": "on"
                }
            ]
        },
        {
            "featureType": "water",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#c7eced"
                }
            ]
        },
        {
            "featureType": "water",
            "elementType": "labels.text.fill",
            "stylers": [
                {
                    "lightness": "-49"
                },
                {
                    "saturation": "-53"
                },
                {
                    "gamma": "0.79"
                }
            ]
        }
    ]
    });
  }

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GMAP']%>&callback=initMap" async defer></script>