config/routes.rb
Rails.application.routes.draw do
  get 'map/index'
  devise_for :users
  root 'users#top'
  get '/map_request', to: 'posts#map', as: 'map_request'
  get '/root_request', to: 'posts#root', as: 'root_request'
  get 'posts/' => 'posts#index'
  get 'management/' => 'users#management'

  resources :users
  resources :posts
  resources :places
  resources :favorites
  resources :images
  resources :comments
  resources :maps, only: [:index]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :posts, only: [:new, :create, :index, :show] do
      resource :favorites, only: [:create, :destroy]
      resource :comments, only: [:create, :edit, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arkhe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
    <%= include_gon %>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="/assets/skippr.min.js" type="text/javascript" charset="utf-8" async defer></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="wrapper clearfix">
      <header class="top">
          <div class="container">
              <nav class="nav navbar-nav navbar-left">
                <% if user_signed_in? %>
                  <%= link_to users_path do %>
                      <%= image_tag "logo2.png", class: 'mypae-image', style: "width: 200px; height: 63px; margin-top: 20px; margin-left: 30px;" %>
                      <% end %>
                <% else %>
                  <span><%= link_to root_path do %>
                      <%= image_tag "logo2.png", class: 'mypae-image', style: "width: 200px; height: 63px; margin-top: 20px; margin-left: 30px;" %>
                      <% end %>
                  <% end %>
                  </span>
              </nav>
                  <ul class="header-page">
                      <% if user_signed_in? && current_user.admin? %>
                          <li class="header-right">
                            <%= link_to "About", root_path, class:"header-link fas fa-book-open" %>
                          </li>
                          <li class="header-right">
                            <%= link_to "New Post", new_post_path, class:"header-link fas fa-walking" %>
                          </li>
                          <li class="header-right">
                            <%= link_to "Admin Mypage", user_path(current_user.id), class: "header-link fas fa-home" %>
                          </li>
                          <li class="header-right">
                            <%= link_to "Users", management_path, class:"header-link fas fa-users" %>
                          </li>
                          <li class="header-right">
                              <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"header-link fas fa-sign-out-alt" %>
                          </li>
                      <% elsif user_signed_in? && !current_user.admin? %>
                          <li class="header-right">
                            <%= link_to "About", root_path, class:"header-link fas fa-book-open" %>
                          </li>
                          <li class="header-right">
                            <%= link_to "New Post", new_post_path, class:"header-link fas fa-walking" %>
                          </li>
                          <li class="header-right">
                            <li class="header-right">
                            <%= link_to "Mypage", user_path(current_user.id), class:"header-link fas fa-home" %>
                            </li>
                          </li>
                          <li class="header-right">
                              <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"header-link fas fa-sign-out-alt" %>
                          </li>
                      <% else %>
                          <li class="header-right">
                              <%= link_to "Sign up", new_user_registration_path, class:"header-link fas fa-user-plus" %>
                          </li>
                          <li class="header-right">
                              <%= link_to "Login", new_user_session_path, class:"header-link fas fa-sign-in-alt" %>
                          </li>
                      <% end %>
                  </ul>
          </div>
      </header>
    <div class="body-container">

        <%= yield %>

    </div>
      <footer class="footer">
          <p class="footer-text">© Yumiko Fukuchi.</p>
      </footer>
    </div>
    </div>
  </body>
</html>